[package]
name = "kbdmod-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.9.0"
regex = "1.8.3"
serde = "1.0.163"
serde_derive = "1.0.163"
serde_json = "1.0.96"
